/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mariopavlov;

public class App {

    public static void main(String[] args) {

        int[] array = new int[] {1, 2, 3, 4, 5, 6, 7, 8, 9};

        ArraySum arraySum = new ArraySum();

        System.out.println(arraySum.calculateSum(array));
        System.out.println(arraySum.calculateRecursive(array, 0, array.length - 1));
    }
}
